-- MySQL Script generated by MySQL Workbench
-- mié 31 mar 2021 14:26:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BioQuiz
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BioQuiz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BioQuiz` ;
USE `BioQuiz` ;

-- -----------------------------------------------------
-- Table `BioQuiz`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BioQuiz`.`User` (
  `idUser` VARCHAR(15) NOT NULL,
  `email` VARCHAR(45) NULL,
  `Name` VARCHAR(45) NULL,
  `Surname` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `Picture` VARCHAR(200) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BioQuiz`.`Topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BioQuiz`.`Topic` (
  `Topic` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Topic`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BioQuiz`.`Questionnaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BioQuiz`.`Questionnaire` (
  `idQuestionnaire` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NULL,
  `Description` MEDIUMTEXT NULL,
  `Difficulty` VARCHAR(45) NULL,
  `Author` VARCHAR(45) NULL,
  `Number of questions` INT NULL,
  `Pass_rate` FLOAT NULL,
  `Topic_Topic` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idQuestionnaire`),
  INDEX `fk_Questionnaire_Topic1_idx` (`Topic_Topic` ASC) VISIBLE,
  CONSTRAINT `fk_Questionnaire_Topic1`
    FOREIGN KEY (`Topic_Topic`)
    REFERENCES `BioQuiz`.`Topic` (`Topic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BioQuiz`.`Question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BioQuiz`.`Question` (
  `idQuestion` INT NOT NULL AUTO_INCREMENT,
  `Question` TEXT NULL,
  `Difficulty` VARCHAR(45) NULL DEFAULT '.',
  `Questionnaire_idQuestionnaire` INT NOT NULL,
  PRIMARY KEY (`idQuestion`, `Questionnaire_idQuestionnaire`),
  INDEX `fk_Question_Questionnaire1_idx` (`Questionnaire_idQuestionnaire` ASC) VISIBLE,
  CONSTRAINT `fk_Question_Questionnaire1`
    FOREIGN KEY (`Questionnaire_idQuestionnaire`)
    REFERENCES `BioQuiz`.`Questionnaire` (`idQuestionnaire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BioQuiz`.`Answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BioQuiz`.`Answer` (
  `idAnswer` INT NOT NULL AUTO_INCREMENT,
  `Answer` TEXT NULL,
  `Correct` TINYINT NULL,
  `Question_idQuestion` INT NOT NULL,
  PRIMARY KEY (`idAnswer`, `Question_idQuestion`),
  INDEX `fk_Answer_Question1_idx` (`Question_idQuestion` ASC) VISIBLE,
  CONSTRAINT `fk_Answer_Question1`
    FOREIGN KEY (`Question_idQuestion`)
    REFERENCES `BioQuiz`.`Question` (`idQuestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BioQuiz`.`User_questionnaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BioQuiz`.`User_questionnaire` (
  `Questionnaire_idQuestionnaire` INT NOT NULL,
  `User_idUser` VARCHAR(15) NOT NULL,
  `Max score` FLOAT NULL,
  `Saved` TINYINT NULL,
  PRIMARY KEY (`Questionnaire_idQuestionnaire`, `User_idUser`),
  INDEX `fk_User_Questionnaire_Questionnaire1_idx` (`Questionnaire_idQuestionnaire` ASC) VISIBLE,
  INDEX `fk_User_questionnaire_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_User_Questionnaire_Questionnaire1`
    FOREIGN KEY (`Questionnaire_idQuestionnaire`)
    REFERENCES `BioQuiz`.`Questionnaire` (`idQuestionnaire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_questionnaire_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `BioQuiz`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
